on:
  workflow_dispatch:
 
permissions:
  contents: read
  id-token: write
  pull-requests: write
 
jobs:
  build:
    environment:
      name: Test
    runs-on:
      group: DataOps
      labels: SHRDEV
    defaults:
      run:
        shell: bash
 
    name: 'This deploys to Production'
    steps:
    - uses: actions/checkout@v3
      with:
          ref: adf_publish
 
   
    - name: Azure Login
      uses: Azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
   
 
       
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: ./devl-demo-adf/PrePostDeploymentScript.Ver2.ps1 -armTemplate "./devl-demo-adf/ARMTemplateForFactory.json" -ResourceGroupName vinayak-rg -DataFactoryName prod-demo-adf -predeployment $true -deleteDeployment $false
        azPSVersion: latest
 
   
 
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
      env:
          # ARM_USE_AZUREREAD: true
          # ARM_USE_OIDC: true
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          ubscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      with:
     
        scope: 'resourcegroup'
        resourceGroupName: 'Shoaib_RG'
        template: ./adfSource01/ARMTemplateForFactory.json
        deploymentMode: Incremental
        parameters: adfSource01/ARMTemplateParametersForFactory.json factoryName=adfTarget01 SqlServer1_properties_typeProperties_server=10.4.5.3 SqlServer1_properties_typeProperties_database=test5463 SqlServer1_properties_typeProperties_userName=admini AzureKeyVault1_properties_typeProperties_baseUrl=https://sqlservercred.vault.azure.net/
   
   
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: ./devl-demo-adf/PrePostDeploymentScript.Ver2.ps1 -armTemplate "./devl-demo-adf/ARMTemplateForFactory.json" -ResourceGroupName vinayak-rg -DataFactoryName prod-demo-adf -predeployment $false -deleteDeployment $true
        azPSVersion: latest
