on:
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
 
jobs:
  build:
    environment:
      name: STG
    runs-on:
      group: DataOps
      labels: SHRSTG
    defaults:
      run:
        shell: bash

    name: 'This deploys to Staging'
    steps:
    - uses: actions/checkout@v3
      with:
          ref: adf_publish
 
 
    - name: Azure Login
      uses: Azure/login@v1
      with:
        
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        enable-AzPSSession: true
        
    - name: Pre-deployment
      uses: Azure/powershell@v1
      with:
       
        inlineScript: pwsh -File ./QG-QC-ADF-DEV-001/PrePostDeploymentScript.ps1 -armTemplate "./QG-QC-ADF-DEV-001/ARMTemplateForFactory.json" -ResourceGroupName rg-db-stg-qc-001 -DataFactoryName QG-QC-ADF-STG-001 -predeployment:$true -deleteDeployment:$false
        azPSVersion: latest
        
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
      with:
        
        scope: 'resourcegroup'
        resourceGroupName: 'rg-db-stg-qc-001'
        template: ./QG-QC-ADF-DEV-001/ARMTemplateForFactory.json
        parameters: factoryName=QG-QC-ADF-STG-001
 
 
    - name: Post-deployment
      uses: Azure/powershell@v1
      with:
        
        inlineScript: pwsh -File ./QG-QC-ADF-DEV-001/PrePostDeploymentScript.ps1 -armTemplate "./QG-QC-ADF-DEV-001/ARMTemplateForFactory.json" -ResourceGroupName rg-db-stg-qc-001 -DataFactoryName QG-QC-ADF-STG-001 -predeployment:$false -deleteDeployment:$true
        azPSVersion: latest
